Set-Alias -Name ga -Value 'git add'
Set-Alias -Name gaa -Value 'git add .'
Set-Alias -Name gaaa -Value 'git add -A'
Set-Alias -Name gcom -Value 'git commit'
Set-Alias -Name gcomm -Value 'git commit -m'
Set-Alias -Name gd -Value 'git diff'
Set-Alias -Name gin -Value 'git init'
Set-Alias -Name glog -Value 'git log'
Set-Alias -Name gpll -Value 'git pull'
Set-Alias -Name gpsh -Value 'git push'
Set-Alias -Name gss -Value 'git status -s'
